GitHub-Commit-Tracker: /tmp/git/Tadimsky/GitHub-Commit-Tracker/repository/src/utils/git.js File Reference
git.js File Reference
Functions
function Git (repo)
Variables
var nodegit = require("nodegit")
var fs = require("fs-extra")
var rimraf = require("rimraf")
var _ = require('lodash')
var Promise = require("bluebird")
module exports Git = Git
Function Documentation
function Git (repo)
Git Library
Parameters
repo The repo information from GitHub events
Definition at line 12 of file git.js.
References _, add(), exists(), fs, Promise, require(), rimraf, and winston.
Variable Documentation
var _ = require('lodash')
Definition at line 4 of file git.js.
Referenced by Git().
var fs = require("fs-extra")
Definition at line 2 of file git.js.
Referenced by Git().
module exports Git = Git
Definition at line 182 of file git.js.
var nodegit = require("nodegit")
Definition at line 1 of file git.js.
var Promise = require("bluebird")
Definition at line 5 of file git.js.
Referenced by Git().
var rimraf = require("rimraf")
Definition at line 3 of file git.js.
Referenced by Git().