GitHub-Commit-Tracker: /tmp/git/Tadimsky/GitHub-Commit-Tracker/repository/src/utils/doxygen.js File Reference
doxygen.js File Reference
Functions
fs exists (sourceDoxyfile, function(exists){if(!exists){winston.error("Doxyfile does not exist at "+sourceDoxyfile);}else{winston.info("Found Doxyfile.");}})
function setupDoxyfile (dst)
function replaceVariables (file, search, value)
function recursiveConfigCopy (file, source, target)
function setConfig (file, values)
function configureDoxy (doxyInfo, dst)
function runDoxygen (doxyFile)
function processRepository (repo)
Variables
var fs = require("fs-extra")
var replace = require("replace")
var Promise = require("bluebird")
var sourceDoxyfile = global.scriptsFolder + "Doxyfile"
var fileVariables
module exports
Function Documentation
function configureDoxy (doxyInfo, dst)
Definition at line 66 of file doxygen.js.
References Promise, setConfig(), and setupDoxyfile().
Referenced by processRepository().
fs exists (sourceDoxyfile , function(exists){if(!exists){winston.error("Doxyfile does not exist at "+sourceDoxyfile);}else{winston.info("Found Doxyfile.");}})
Referenced by Git().
function processRepository (repo)
Definition at line 104 of file doxygen.js.
References configureDoxy(), Promise, runDoxygen(), and winston.
function recursiveConfigCopy (file, source, target)
Definition at line 49 of file doxygen.js.
References replaceVariables().
Referenced by setConfig().
function replaceVariables (file, search, value)
Definition at line 40 of file doxygen.js.
References paths, and replace.
Referenced by recursiveConfigCopy().
function runDoxygen (doxyFile)
Definition at line 77 of file doxygen.js.
References doxygen, Promise, require(), and winston.
Referenced by processRepository().
function setConfig (file, values)
Definition at line 62 of file doxygen.js.
References recursiveConfigCopy().
Referenced by configureDoxy().
function setupDoxyfile (dst)
Definition at line 29 of file doxygen.js.
References fs, Promise, sourceDoxyfile, and winston.
Referenced by configureDoxy().
Variable Documentation
module exports
Initial value:
= {
    process: function(git, repo) {
        return new Promise(function(resolve, reject) {
            processRepository(repo).then(function() {
                git.createGitHubPages().then(function() {
                    fs.copy(repo.directory.docs, repo.directory.repo, function(err){
                        if (err) return winston.error(err);
                        winston.info("Copied docs to repo.");
                        git.add().then(function() {
                            git.commit("Added Doxygen documentation").then(function() {
                                git.push("gh-pages", true).then(function() {
                                    winston.info("Pushed Doxygen docs.");
                                    git.checkout('master').then(function() {
                                       resolve();
                                    }).catch(function(err) {
                                        reject(err);
                                    });
                                });
                            });
                        });
                    });
                });
            });
        });
    }
}
Definition at line 129 of file doxygen.js.
var fileVariables
Initial value:
= {
    project: {
        title: "%PROJECT_TITLE%",
        version: "%PROJECT_VERSION%"
    },
    output: {
        location: "%OUTPUT_DIRECTORY%"
    },
    input: {
        location: "%INPUT_DIRECTORY%"
    }
}
Definition at line 16 of file doxygen.js.
var fs = require("fs-extra")
Definition at line 1 of file doxygen.js.
Referenced by setupDoxyfile().
var Promise = require("bluebird")
Definition at line 3 of file doxygen.js.
Referenced by configureDoxy(), processRepository(), runDoxygen(), and setupDoxyfile().
var replace = require("replace")
Definition at line 2 of file doxygen.js.
Referenced by replaceVariables().
var sourceDoxyfile = global.scriptsFolder + "Doxyfile"
Definition at line 5 of file doxygen.js.
Referenced by setupDoxyfile().