GitHub-Commit-Tracker: /tmp/git/Tadimsky/GitHub-Commit-Tracker/repository/src/utils/gh-pages.js File Reference
gh-pages.js File Reference
Functions
function replaceVariables (file, search, value)
function recursiveConfigCopy (file, source, target)
function setPageContent (file, values)
function generatePages (dst)
function configureGHPages (projectInfo, dst)
function processRepository (repo)
Variables
var fs = require("fs-extra")
var replace = require("replace")
var Promise = require("bluebird")
var fileVariables
module exports
Function Documentation
function configureGHPages (projectInfo, dst)
Definition at line 52 of file gh-pages.js.
References generatePages(), Promise, and setPageContent().
Referenced by processRepository().
function generatePages (dst)
Definition at line 42 of file gh-pages.js.
References fs, and Promise.
Referenced by configureGHPages().
function processRepository (repo)
Definition at line 63 of file gh-pages.js.
References configureGHPages(), and Promise.
function recursiveConfigCopy (file, source, target)
Definition at line 25 of file gh-pages.js.
References replaceVariables().
Referenced by setPageContent().
function replaceVariables (file, search, value)
Definition at line 16 of file gh-pages.js.
References paths, and replace.
Referenced by recursiveConfigCopy().
function setPageContent (file, values)
Definition at line 38 of file gh-pages.js.
References fileVariables, and recursiveConfigCopy().
Referenced by configureGHPages().
Variable Documentation
module exports
Initial value:
= {
    process: function(repo) {
        return new Promise(function(resolve, reject) {
            processRepository(repo).then(function() {
                winston.info('Setup GH-Pages.');
                resolve();
            });
        });
    }
}
Definition at line 84 of file gh-pages.js.
var fileVariables
Initial value:
= {
    project: {
        title: "%PROJECT_TITLE%",
        version: "%PROJECT_VERSION%"
    },
    repo: {
        name: "%REPO_NAME%",
        owner: "%REPO_OWNER%"
    }
}
Definition at line 5 of file gh-pages.js.
Referenced by setPageContent().
var fs = require("fs-extra")
Definition at line 1 of file gh-pages.js.
Referenced by generatePages().
var Promise = require("bluebird")
Definition at line 3 of file gh-pages.js.
Referenced by configureGHPages(), generatePages(), and processRepository().
var replace = require("replace")
Definition at line 2 of file gh-pages.js.
Referenced by replaceVariables().