GitHub-Commit-Tracker: /tmp/git/Tadimsky/GitHub-Commit-Tracker/repository/repoTracker/packages/users/server/controllers/users.js File Reference
users.js File Reference
Functions
function sendMail (mailOptions)
Variables
use strict
var mongoose = require('mongoose')
var User = mongoose.model('User')
var async = require('async')
var config = require('meanio').loadConfig()
var crypto = require('crypto')
var nodemailer = require('nodemailer')
var templates = require('../template')
exports authCallback
exports signin
exports signout
exports session
exports create
exports me
exports user
exports resetpassword
exports forgotpassword
Function Documentation
function sendMail (mailOptions)
Send reset password email
Definition at line 171 of file users.js.
References config, mailOptions, and nodemailer.
Variable Documentation
var async = require('async')
Definition at line 8 of file users.js.
exports authCallback
Initial value:
= function(req, res) {
  res.redirect('/');
}
Auth callback
Definition at line 17 of file users.js.
var config = require('meanio').loadConfig()
Definition at line 9 of file users.js.
Referenced by sendMail().
exports create
Create user
Definition at line 49 of file users.js.
var crypto = require('crypto')
Definition at line 10 of file users.js.
Referenced by getRandomString().
exports forgotpassword
Callback for forgot password link
Definition at line 182 of file users.js.
exports me
Initial value:
= function(req, res) {
  res.json(req.user || null);
}
Send User
Definition at line 107 of file users.js.
var mongoose = require('mongoose')
Module dependencies.
Definition at line 6 of file users.js.
var nodemailer = require('nodemailer')
Definition at line 11 of file users.js.
Referenced by sendMail().
exports resetpassword
Resets the password
Definition at line 131 of file users.js.
exports session
Initial value:
= function(req, res) {
  res.redirect('/');
}
Session
Definition at line 42 of file users.js.
exports signin
Initial value:
= function(req, res) {
  if (req.isAuthenticated()) {
    return res.redirect('/');
  }
  res.redirect('#!/login');
}
Show login form
Definition at line 24 of file users.js.
exports signout
Initial value:
= function(req, res) {
  req.logout();
  res.redirect('/');
}
Logout
Definition at line 34 of file users.js.
use strict
Definition at line 1 of file users.js.
var templates = require('../template')
Definition at line 12 of file users.js.
var User = mongoose.model('User')
Definition at line 7 of file users.js.
exports user
Initial value:
= function(req, res, next, id) {
  User
    .findOne({
      _id: id
    })
    .exec(function(err, user) {
      if (err) return next(err);
      if (!user) return next(new Error('Failed to load User ' + id));
      req.profile = user;
      next();
    });
}
Find user by id
Definition at line 114 of file users.js.