GitHub-Commit-Tracker: /tmp/git/Tadimsky/GitHub-Commit-Tracker/repository/src/app.js File Reference
app.js File Reference
Functions
winston remove (winston.transports.Console)
winston add (winston.transports.Console,{colorize:true, timestamp:true})
if (process.env.environment=="development")
app use (logger('dev'))
app use (bodyParser.json({limit: '5mb'}))
app use (bodyParser.urlencoded({extended:false, limit:'5mb'}))
app use ('/github', github)
Variables
global scriptsFolder = __dirname + "/../scripts/"
global pagesFolder = __dirname + "/../gh-pages/"
global winston = require('winston')
var express = require('express')
var path = require('path')
var favicon = require('serve-favicon')
var logger = require('morgan')
var cookieParser = require('cookie-parser')
var bodyParser = require('body-parser')
var routes = require('./routes/index')
var github = require('./routes/github')
var app = express()
module exports = app
Function Documentation
winston add (winston.transports. Console, {colorize:true, timestamp:true})
Referenced by Git().
if (process.env. environment = = "development")
Definition at line 22 of file app.js.
winston remove (winston.transports. Console)
app use (logger('dev'))
app use (bodyParser. json{limit: '5mb'})
app use (bodyParser. urlencoded{extended:false, limit:'5mb'})
app use ('/github' , github)
Variable Documentation
var app = express()
Definition at line 20 of file app.js.
var bodyParser = require('body-parser')
Definition at line 15 of file app.js.
var cookieParser = require('cookie-parser')
Definition at line 14 of file app.js.
module exports = app
Definition at line 56 of file app.js.
var express = require('express')
Definition at line 10 of file app.js.
var favicon = require('serve-favicon')
Definition at line 12 of file app.js.
var github = require('./routes/github')
Definition at line 18 of file app.js.
var logger = require('morgan')
Definition at line 13 of file app.js.
global pagesFolder = __dirname + "/../gh-pages/"
Definition at line 2 of file app.js.
var path = require('path')
Definition at line 11 of file app.js.
var routes = require('./routes/index')
Definition at line 17 of file app.js.
global scriptsFolder = __dirname + "/../scripts/"
Definition at line 1 of file app.js.
global winston = require('winston')
Definition at line 3 of file app.js.
Referenced by Git(), handlePing(), handlePush(), handleWiki(), processRepository(), runDoxygen(), and setupDoxyfile().