var searchData=
[
  ['defaultprefix',['defaultPrefix',['../da/dcd/controllers_2mean_user_8js.html#ad77c767871763ebb6fa634606a22e8c1',1,'meanUser.js']]],
  ['describe',['describe',['../d8/d07/server_2tests_2articles_8js.html#a439f75758409c3323c48a9c079af31c1',1,'describe(&apos;&lt; Unit Test &gt;&apos;, function(){describe(&apos;Model Article:&apos;, function(){beforeEach(function(done){user=new User({name: &apos;Full name&apos;, email: &apos;test @test.com&apos;, username: &apos;user&apos;, password: &apos;password&apos;});user.save(function(){article=new Article({title: &apos;Article Title&apos;, content: &apos;Article Content&apos;, user:user});done();});});describe(&apos;Method Save&apos;, function(){it(&apos;should be able to save without problems&apos;, function(done){return article.save(function(err){should.not.exist(err);article.title.should.equal(&apos;Article Title&apos;);article.content.should.equal(&apos;Article Content&apos;);article.user.should.not.have.length(0);article.created.should.not.have.length(0);done();});});it(&apos;should be able to show an error when try to save without title&apos;, function(done){article.title= &apos;&apos;;return article.save(function(err){should.exist(err);done();});});it(&apos;should be able to show an error when try to save without content&apos;, function(done){article.content= &apos;&apos;;return article.save(function(err){should.exist(err);done();});});it(&apos;should be able to show an error when try to save without user&apos;, function(done){article.user={};return article.save(function(err){should.exist(err);done();});});});afterEach(function(done){article.remove();user.remove();done();});});}):&#160;articles.js'],['../d5/d7a/test_2spec_2controllers_2about_8js.html#a8d4f883c4dcf584b955647065a712b1d',1,'describe(&apos;Controller:AboutCtrl&apos;, function(){beforeEach(module(&apos;webApp&apos;));var AboutCtrl, scope;beforeEach(inject(function($controller, $rootScope){scope=$rootScope.$new();AboutCtrl=$controller(&apos;AboutCtrl&apos;,{$scope:scope});}));it(&apos;should attach a list of awesomeThings to the scope&apos;, function(){expect(scope.awesomeThings.length).toBe(3);});}):&#160;about.js'],['../d0/df4/test_2spec_2controllers_2main_8js.html#a8516756bfadf8054af656d7a46b7441d',1,'describe(&apos;Controller:MainCtrl&apos;, function(){beforeEach(module(&apos;webApp&apos;));var MainCtrl, scope;beforeEach(inject(function($controller, $rootScope){scope=$rootScope.$new();MainCtrl=$controller(&apos;MainCtrl&apos;,{$scope:scope});}));it(&apos;should attach a list of awesomeThings to the scope&apos;, function(){expect(scope.awesomeThings.length).toBe(3);});}):&#160;main.js'],['../d7/d9c/hook_8js.html#a8f452825f94dae0214684ae71e1dd3ec',1,'describe(&apos;Send Push Event to Server&apos;, function(){it(&apos;success&apos;, function(done){var req=request(&quot;http://colab-sbx-44.oit.duke.edu:3000/github/webhook&quot;);req.post(&apos;/&apos;).set(&apos;X-GitHub-Event&apos;, &apos;push&apos;).send(request_data).expect(200, done);})}):&#160;hook.js']]],
  ['destroy',['destroy',['../dd/d53/server_2controllers_2articles_8js.html#a18e2d843c6aed238effec5579b1f9620',1,'articles.js']]],
  ['development_2ejs',['development.js',['../d0/d45/development_8js.html',1,'']]],
  ['dist',['dist',['../dd/d3d/src_2client_2_gruntfile_8js.html#ad1f1bfac397a6813156294eef8c4f713',1,'Gruntfile.js']]],
  ['doxygen',['doxygen',['../d8/d93/routes_2github_8js.html#ac0f45113efab0d3bd14205b3fa8bc95a',1,'github.js']]],
  ['doxygen_2ejs',['doxygen.js',['../df/d1e/doxygen_8js.html',1,'']]]
];
